# Site settings
encoding: utf-8
exclude: ['node_modules']

title: Up.front
email: mail@kristinaschneider.com
description: > # this means to ignore newlines until "baseurl:"
  "Up.front – Meetup for the web design and front end community in Berlin"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://up.front.ug" # the base hostname & protocol for your site
twitter_username: upfront_ug
facebook_username:  up.front.ug

permalink: pretty

sass:
    style: compressed

future: true

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      time: 7:45pm
      layout: post
